package com.example.demo.entities;

import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RequestToService generated by hbm2java
 */
@Entity
@Data
@Table(name = "request_to_service", catalog = "ops_pay_service")
public class RequestToService implements java.io.Serializable {

    @Id
    @Column(name = "OBJECT_ID", unique = true, nullable = false)
    private long objectId;

    @Column(name = "REQUEST_SERVICE_ID", length = 100)
    private String requestServiceId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "REQUEST_TIME", length = 19)
    private Date requestTime;

    @Column(name = "REQUEST_BODY", length = 65535)
    private String requestBody;

    @Column(name = "RESPONSE_SERVICE_ID", length = 100)
    private String responseServiceId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "RESPONSE_TIME", length = 19)
    private Date responseTime;

    @Column(name = "RESPONSE_CODE", length = 30)
    private String responseCode;

    @Column(name = "RESPONSE_MSG", length = 65535)
    private String responseMsg;

    @Column(name = "RESPONSE_BODY", length = 65535)
    private String responseBody;

}